# Generated by Django 4.1.2 on 2022-12-04 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_shippingaddress2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress2',
        ),
    ]
