# Generated by Django 4.1.2 on 2022-10-19 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_producer_alter_products_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.producer'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=999999999),
        ),
    ]
